### ISSUE TITLE
In-app reviews for iOS

### ISSUE THREAD

**Issue by ilyakar** [jlyman/react-native-rating-requestor#24] opened 2018-01-30 15:50 UTC
I cannot tell whether this plugin supports iOS 10.3+ feature of in-app reviews. If not, can we have this support?

**Comment by jlyman** [comment] 2018-01-30 15:58
The plugin supports the new store review URL, but does not use the iOS SDK controller for doing in-app reviews. That's next on my list of thing to support, but in the meantime there's a fork that already accomplishes that, see #16.

The current usage still works, however, it's just not as slick. Apple still allows direct linking to the store's review page for cases where the user wants to directly leave a review, because the SKStoreReviewController *will not always show* when requested, by design.

**Comment by ilyakar** [comment] 2018-01-30 18:09
Yes it would be great to support. It would fit really well with your “happy path” concept. First 3-4 prompts it would try to make the in-app review requests. If the user still continues to click “later” then they would start seeing the store redirect prompts.

**Comment by jlyman** [comment] 2019-08-01 11:27
Should be resolved by #16.

**Closed by jlyman** 2019-08-01 11:27 UTC
